# Generated by Django 5.0.9 on 2024-12-18 03:09

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='research/%Y/%m/%d/')),
                ('titre', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titre')),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('resumé', models.TextField()),
                ('members', models.ManyToManyField(to='members.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FAQ', to='research.projetrecherche')),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='research_fa_created_2572b2_idx')],
            },
        ),
    ]
