# Generated by Django 5.0.9 on 2024-12-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_profile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='research/%Y/%m/%d/')),
                ('titre', models.CharField(max_length=200)),
                ('problematique', models.TextField()),
                ('methode_recherche', models.TextField()),
                ('domaines_application', models.TextField()),
                ('resultats_impacts', models.TextField()),
                ('resumé', models.TextField()),
                ('members', models.ManyToManyField(to='members.profile')),
            ],
        ),
    ]
