# Generated by Django 5.0.9 on 2024-12-14 20:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetrecherche',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='titre'),
        ),
    ]
