# Generated by Django 5.0.9 on 2024-12-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(choices=[('Mr', 'monsieur'), ('Mme', 'madame'), ('Mll', 'mademoiselle'), ('Dr', 'docteur'), ('Pr', 'professeur')], default='Mr', max_length=100),
        ),
    ]
