# Generated by Django 5.0.9 on 2024-12-31 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
