# Generated by Django 5.0.9 on 2024-12-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0003_alter_title_name'),
        ('members', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expertise',
            field=models.ManyToManyField(to='administrateur.expertisefield'),
        ),
    ]
