# Generated by Django 5.0.9 on 2024-12-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='google_scholar',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='researchgate',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('etudiant_chercheur', 'Étudiant chercheur'), ('chercheur', 'Chercheur'), ('administrateur', 'Administrateur'), ('consultant', 'Consultant'), ('scientifique', 'Scientifique')], default='administrateur', max_length=100),
        ),
    ]
