# Generated by Django 5.0.9 on 2024-12-02 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0003_alter_title_name'),
        ('members', '0004_profile_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administrateur.title'),
        ),
    ]
