# Generated by Django 5.0.9 on 2024-12-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='titre',
            new_name='name',
        ),
    ]
