# Generated by Django 5.1.3 on 2024-11-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('problematique', models.TextField()),
                ('methode_recherche', models.TextField()),
                ('domaines_application', models.TextField()),
                ('resultats_impacts', models.TextField()),
                ('members', models.ManyToManyField(to='members.member')),
            ],
        ),
    ]
