# Generated by Django 5.1.3 on 2024-11-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetrecherche',
            name='resumé',
            field=models.TextField(default=''),
        ),
    ]
