# Generated by Django 5.1.3 on 2024-11-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_projetrecherche_resumé'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetrecherche',
            name='resumé',
            field=models.TextField(),
        ),
    ]
