# Generated by Django 5.1.3 on 2024-11-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_profile_picture_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='member',
            name='title',
        ),
        migrations.DeleteModel(
            name='ExpertiseField',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
